site_name: Marcinkowe mądrości
plugins:
  - typeset
#  - to-pdf
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite     # Podświetlanie składni
  - pymdownx.snippets:        # Wklejanie zerwnętrznych plików do codeblocków
      base_path:
        - docs
      check_paths: true       # Lepiej raportuje błędy jak nie znajdzie wklejanego pliku
  - pymdownx.superfences      # ramki, zakładki, annotatacje
  - admonition                # Ramki z Uwagami
  - pymdownx.details
  - pymdownx.tabbed:          # zakładki
      alternate_style: true
  - attr_list                 # Emoji i annotace i custom css
  - md_in_html                # annotacje w gołym md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
          - .icons
  - pymdownx.critic           # Dodatkowe formatowania, np podświetlanie, przekreślanie
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
theme:
  name: material
  custom_dir: overrides  # Ważne! Włącza overrides dla seksji `icon:`s
  logo: assets/ibm-eye-bee-m-black_on_trans_vertical.svg
  features:
    - content.code.copy     # kopiwanie kodu po całości
    - content.code.select   # Koiowanie kodu linijkami
    - content.code.annotate # Adnotacje w code blockach
    - navigation.indexes    # Żeby kliknięcie w rozwijane sekcje pokazywało index.md lub README.md
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: orange

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: orange

nav:
  - Home: README.md
  - Ansible: 
    - Tips & tricks: ansible/index.md
    - Power HMC: ansible/POWER.md
  - DB2: 
    - db2/index.md
    - Instalacja: db2/setup.md
    - Bazy: db2/db.md
    - Backup & Restore: db2/back_n_rest.md
    - Tips & tricks: db2/tips.md
  - Git: git/index.md
  - GPFS: GPFS/index.md
  - ISP:
    - ISP/README.md
    - Qury SQLowe: ISP/SQL.md
    - Setup serwera: 
        - OS: ISP/setup_os.md
        - Instancja: ISP/setup_instance.md
        - Taśmy: ISP/setup_tapes.md
        - Maintenance: ISP/setup_maint.md
        - Kontenery (dir): ISP/setup_dc.md
        - Kontenery (cloud): ISP/setup_cc.md
        - LANFree: ISL/setup_STA.md
        - Upgrade: ISP/upgrade.md
        - Użyteczne opcje: ISP/srv_opts.md
    - Klienci:
      - Klient BA: ISP/ba.md
      - TDP4VE: ISP/TDP4VE.md 
      - DB2: ISP/db2.md
  - LNX: 
    - LNX/README.md
    - MPIO: LNX/MPIO_and_SAN.md
    - lin_tape: LNX/lin_tape.md
    - Multipath - User friendly names: LNX/lsvdisk2mpio_friendly_names.md
    - Sieć:
      - Bonding: LNX/bond.md
      - VLAN: LNX/vlan.md
    - X11: LNX/x11.md
  - mkdocs: 
    - mkdocs/index.md
    - Ikony: mkdocs/icons.md
    - Obrazki: mkdocs/img.md
  - Power:
    - Power/index.md
    - HMC: Power/HMC.md
    - VIOS: Power/VIOS.md
  - Unix:
      - UNX/index.md
  - Virt: 
    - virt/README.md
    - Libvirt: virt/libvirt.md
    - QCOW2 i inne dyski: virt/qemu-img.md
  - WinDOS: 
    - WinDOS/index.md
    - WinDOS/PS.md
