site_name: Marcinkowe mądrości
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite     # Podświetlanie składni
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition                # Ramki z Uwagami
  - pymdownx.details
  - pymdownx.superfences      # ramki i zakładki
  - pymdownx.tabbed:          # zakładki
      alternate_style: true
  - attr_list                 # Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: orange

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: orange

nav:
  - Home: README.md
  - Ansible: ansible/index.md
  - DB2: 
    - Instalacja: db2/setup.md
    - Bazy: db2/db.md
    - Tips & tricks: db2/tips.md
  - Git: git/index.md
  - GPFS: GPFS/index.md
  - ISP:
    - Qury SQLowe: ISP/SQL.md
    - Setup serwera: 
        - OS: ISP/setup_os.md
        - Instancja: ISP/setup_instance.md
        - Taśmy: ISP/setup_tapes.md
        - Maintenance: ISP/setup_maint.md
        - Kontenery (dir): ISP/setup_dc.md
        - Kontenery (cloud): ISP/setup_cc.md
        - LANFree: ISL/setup_STA.md
    - Klienci:
      - Klient BA: ISP/ba.md
      - TDP4VE: ISP/TDP4VE.md 
      - DB2: ISP/db2.md
  - LNX: 
    - MPIO: LNX/MPIO_and_SAN.md
    - lin_tape: LNX/lin_tape.md
    - Multipath - User friendly names: LNX/lsvdisk2mpio_friendly_names.md
    - Sieć:
      - Bonding: LNX/bond.md
      - VLAN: LNX/vlan.md
    - X11: LNX/x11.md
  - mkdocs: mkdocs/index.md
  - Power:
    - HMC: Power/HMC.md
    - VIOS: Power/VIOS.md
  - Virt: virt/index.md
  - WinDOS: WinDOS/index.md
